# Generated by Django 4.2.4 on 2024-02-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='company',
            field=models.CharField(choices=[('Gimi', 'Gimi'), ('GBL', 'GBL'), ('GPB', 'GPB'), ('GIR', 'GIR')], default='Gimi', max_length=4, verbose_name='Company'),
        ),
    ]
