# Generated by Django 4.2.4 on 2024-02-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_contract_freight_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='control_number',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Control Number'),
        ),
    ]
