# Generated by Django 4.2.4 on 2024-03-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_alter_contract_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='control_number',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Control Number'),
        ),
    ]
