# Generated by Django 4.2.4 on 2024-03-14 14:46

import apps.users.validators.superuser
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(choices=[('Gimi', 'Gimi'), ('GBL', 'GBL'), ('GPB', 'GPB'), ('Group', 'Group')], default='Gimi', max_length=5, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[apps.users.validators.superuser.valid_phone], verbose_name='Phone'),
        ),
    ]
